version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/server/client
    steps:
      - checkout:
          path: ~/server
      - run: echo "testing"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/server/client
    steps:
      - checkout:
          path: ~/server
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
      - run:
          name: Commit to Github
          command: |
            sed -i -e 's/\/node_modules//' .gitignore
            sed -i -e 's/\/build//' .gitignore
            git config credential.helper 'cache --timeout=120'
            git config user.email "orinayooyelade@gmail.com"
            git config user.name "orinayo"
            git add -A
            git commit -m "Trigger deployment"
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master