version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/server/client
    steps:
      - checkout:
          path: ~/server
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/server/client
    steps:
      - checkout:
          path: ~/server
      - run: echo "testing"
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master